### ISSUE TITLE
spyglass: running jobs show invalid start time

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/test-infra#11096]
As in here:

![screenshot from 2019-02-01 16-35-09](https://user-images.githubusercontent.com/7328370/52156826-7210a780-263f-11e9-80a8-f5c72b73c352.png)

/area deck/spyglass
/cc @Katharine

**Comment by stevekuznetsov** [comment]
We're seeing this on _all_ currently running jobs

**Comment by imkin** [comment]
I just experienced this at https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-build/92561
Screen shot 
<img width="1428" alt="screen shot 2019-02-25 at 3 42 21 pm" src="https://user-images.githubusercontent.com/2793249/53376919-ee339d80-3914-11e9-928f-46617dfd2636.png">

UptoDate: Firefox 65.0.1

Web Console stack trace:
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2019-02-25 22:36:30 +0000 UTC, _f: undefined, _strict: undefined, _locale: [object Object]
k/<@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:3215
l@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:21280
_@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:21161
Ot@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:21057
l@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:22019
Tt@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:21999
xt@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:22113
n@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:54
ji@https://prow.k8s.io/spyglass/static/metadata/script_bundle.min.js:1:52383
script_bundle.min.js:1:2801
```

**Comment by ibzib** [comment]
We should just keep the original date string when JS fails to parse it.

**Comment by Katharine** [comment]
This is fixed by #11466

**Comment by imkin** [comment]
@Katharine I still face this in firefox btw. Are you suggesting we do not supporting firefox?

**Comment by Katharine** [comment]
Firefox should be fine!

We haven't deployed the fix yet (but will do shortly), so if you're using prow.k8s.io you will still see this bug. If you're running your own instance, that would be surprising.

**Comment by imkin** [comment]
Ah thanks. I assumed it based on your comment (use chrome). Thanks. No I do not have my own instance of prow.

**Comment by Katharine** [comment]
The fixed version is now deployed, so it would be interesting to know whether you still have this problem.

**Comment by imkin** [comment]
<img width="1429" alt="screen shot 2019-02-26 at 4 38 25 pm" src="https://user-images.githubusercontent.com/2793249/53456887-feb34900-39e4-11e9-94d5-7a12c407e777.png">
It works now. screenshot attached.
