### ISSUE TITLE
Multi arch for test-infra/images

### ISSUE THREAD

**Issue by lubinszARM** [kubernetes/test-infra#16588]
This issue is for pushing multi-architecture images for test-infra/images, so that the specific jobs can be scheduled by Prow into Arm64 nodes.
 * [ ]  kubekins-test
 * [ ]  builder, google/cloud-sdk

If a typical k8s-e2e-kind-test prow job was scheduled into an Arm64 k8s cluster, a POD contains at least the following images, so we should make them to support Arm64:
 * [ ]  kubekins-e2e
 * [ ]  bootstrap
 * [ ]  sidecar
 * [ ]  initupload
 * [ ]  clonerefs

**Comment by lubinszARM** [comment]
cc @BenTheElder @zhlhahaha

**Comment by BenTheElder** [comment]
This seems quite a bit ahead of ourselves without any plan for Prow on such nodes.

cc @dims @mkumatag

**Comment by mkumatag** [comment]
Interesting, I was thinking about this for quite some time. Can we have individual architecture's cluster running anywhere in the word and prow scheduling respective arch's job into those clusters and get things done?

**Comment by BenTheElder** [comment]
I don't see why we would go to all that trouble over having jobs ssh etc.
To run test clusters on whatever arch.

We barely have people helping maintain the existing infra with relatively
self managing GKE clusters. I can't see us wanting to maintain long running
bespoke clusters on various infra on top of porting and cross building all
of these equally barely maintained CI images ...

**Comment by lubinszARM** [comment]
This issue is used to track it.
We will test it in our local hybrid CI cluster firstly.
Finally we will update this issue and then decide whether to do this.
Thanks.

**Comment by zhlhahaha** [comment]
Hi, @BenTheElder @mkumatag @dims , here is some update, issues and plans about prow test on ARM. Please feel free to tell me if there is anything not clear. Looking forward your suggestion.

**Update:**
- We deployed a prow cluster on x86 and a kubernetes cluster on ARM. 
- enabling test pods on ARM k8s cluster 
- Set a presubmit jobs, "pull-kubernetes-conformance-image-test", on ARM k8s cluster, it can be run successfully and all kind-conformance test passed, result has upload to [gs](https://console.cloud.google.com/storage/browser/k8s-conformance-arm/logs/test-pr/pull-kubernetes-conformance-image-test/20200319-080338-3387b4887970e1eb-7055/) 

**Issues:**
- The kubekins-e2e image for arm platform is build by ourselves.
- In the prow jobs, we still use bootstrap.py because we are not able to use podutils as the images, bootstrap, sidecar, initupload, clonerefs only support x86 platform.
- In order to trigger the presubmit jobs, I use my private kubernetes library in github.com.
- The script "kind-conformance-image-e2e.sh" is only support x86 platform. I submit a [patch](https://github.com/kubernetes/test-infra/pull/16812) for mutliarch support, but it is not enough. As the version of kind in the script is 0.6.0, and the binary do not works well on Arm Platform. We use kind that compiled from most resent source code.

**Plans:**
- enable kubekins-e2e image build for multi-arch
- enable bootstrap, sidecar, initupload, clonerefs build for multi-arch
-  looking forward new release of kind

**Comment by BenTheElder** [comment]
I still don't think we need a prow on ARM at all, we can let a prow job on the normal build cluster SSH / whatever to ARM infra the same as we do when we bring up cluster on AWS / GCP.

**Comment by lubinsz** [comment]
Hi @BenTheElder 
I agree with you. 
According to our reserach, prow cluster is still on x86, and we can create a arm64 build cluster, and let some typical test prow jobs running on Arm64, such as pull-kubernetes-conformance-image-test.
The following figure is Prow's microservice architecture for the test job of 'pull-kubernetes-conformance-image-test' on Arm64.

![image](https://user-images.githubusercontent.com/1996245/77398539-b1212f80-6de2-11ea-9bf0-7a867f305740.png)

**Comment by lubinszARM** [comment]
cc @jingzhao123

**Comment by zhlhahaha** [comment]
Hi @BenTheElder @spiffxp @mkumatag 
Can we enable prow utility images for multi-arch?
Here are some reasons why we need prow utility images running on multi-arch.
1. The k8s conformance test running on ARM which you can see in https://testgrid.k8s.io/sig-node-arm64, are triggered by shell script currently. And we want to sync the test flow with kuternetes test-infra by using prow.
2. Some other projects like kubevirt, kubeflow, they all use prow for their CI lane. We are trying to enable ARM CI testing for these projects.

**Comment by rmohr** [comment]
> I still don't think we need a prow on ARM at all, we can let a prow job on the normal build cluster SSH / whatever to ARM infra the same as we do when we bring up cluster on AWS / GCP.

This can definitely work. However consider how much simpler it is to onboard different architectures for opensource projects, if you just pass a new cluster context to prow and put a label on your job.

As far as I can see, it would mostly just be necessary to cross-compile a few plain docker binaries. clonerefs may need a multiarch base image with git (building that with qemu-user should be streight forward. We do that in kubevirt too on our amd64 machines). The bootstrap image is in my opinion not really needed. It would be about

```
sidecar
initupload
clonerefs
```

only.

@BenTheElder would you see a way where we could maintain this in this repo? We basically have the same issue with ppc64 too btw.

**Comment by LorbusChris** [comment]
Looks like this hasn't been solved yet
/reopen

For OpenShift, we're currently in the process of standing up `arm64` test infra, and I think at least the following images are going to be needed:
- clonerefs
- entrypoint
- initupload
- sidecar

@BenTheElder is this still considered something that could be done and maintained in this repo?

cc @stevekuznetsov

**Comment by BenTheElder** [comment]
I think you're going to find it a bit challenging to produce these in a multi-arch way with the current build tools versus at least one arch at a time and some post processing. But ultimately it's the call of the active prow/OWNERS as to what's acceptable.

The original context was ensuring kubernetes CI has arm coverage for which we didn't need this at all (versus creating clusters under test on ARM), that conversation is what brought me here, I have no vested interest one way or another otherwise.

**Comment by LorbusChris** [comment]
@BenTheElder since you mention the _current build tools_: Are there any reasons Bazel is used for building in this repo other than historical ones?
The main k8s repo has removed Bazel build support recently - are there any plans to do the same with this repository?

**Comment by BenTheElder** [comment]
> The main k8s repo has removed Bazel build support recently - are there any plans to do the same with this repository?

No, there are not. We were very clear in the KEP that it only applied to the Kubernetes repo and its requirements. The reasoning was also specific to kubernetes and its multiple concurrent build systems for the same components. There's more on that in the KEP.

> Are there any reasons Bazel is used for building in this repo other than historical ones?

I'd rather not re-litigate that here, there are pros and cons to any option. Other people should have input on that as well. But even if there weren't, doing so for the whole repo would be a pretty involved undertaking.

Also important to note: This repo has never been 100% bazel, e.g. we have other images that do use dockerfiles for various reasons. So that's not a direct obstacle anyhow, rather most of the repo including prow opt to use it.

It's also possible that you will find it is easier to do multi-arch now. I don't know, as I don't work with this anymore.

@cjwagner @stevekuznetsov and others in prow/OWNERS should be deciding about prow spefiically.

**Comment by BenTheElder** [comment]
FWIW I also think prow should be moved to it's own repo as well, with less coupling to the rest of the test-infra, but that's similarly not something anyone is currently willing to staff. https://github.com/kubernetes/test-infra/issues/11782

**Comment by zhlhahaha** [comment]
Hi, @LorbusChris, do you have any plan to enable building multi-arch bootstrap image (https://github.com/kubernetes/test-infra/tree/master/images/bootstrap)?

**Comment by zhlhahaha** [comment]
cc: @chendave

**Comment by LorbusChris** [comment]
@zhlhahaha no, I don't but you should be able to take the two images linked above as references for how to do it.

**Comment by chendave** [comment]
/remove-lifecycle rotten
/remove-lifecycle frozen

someone has interests on this can still input their comments here.

**Comment by raelga** [comment]
Is there a any updates on ARM64 for Prow?

**Comment by BenTheElder** [comment]
Prow can run test pods on arm64 and doesn't live in this repo anymore.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/prow
