### ISSUE TITLE
Tide does not surface merge failures when rebase is requested but not possible

### ISSUE THREAD

**Issue by petr-muller** [kubernetes/test-infra#25088]
**What happened**:

We had a repository that configured Tide to use `rebase` merge method:

```yaml
tide:
  merge_method:
    openshift/cluster-api-provider-azure: rebase
```

Tide got stuck merging a PR that GH would allow to merge via a merge commit, but not with rebase:

![rebase](https://user-images.githubusercontent.com/712614/152177496-1b4033a2-5f28-4ebd-a74c-28c15d3fdd8b.png)

(when I selected "merge" in the dropdown above, I would be allowed to merge the PR)

The problem is that this was not in any way surfaced by Tide to the user. The tide status was saying "In Merge Pool", Tide history showed a list of attempted `MERGE` actions, and I only found out after looking to the logs where I saw:

```
PR is unmergable. Do the Tide merge requirements match the GitHub settings for the repo? This branch can't be rebased
```

**What you expected to happen**:

Tide status should say something like "Tide is not mergeable using "rebase" method" or something similar.

**Anything else we need to know?**:

/area prow/tide

**Comment by alexander-demichev** [comment]
Looking at code https://github.com/kubernetes/test-infra/blob/master/prow/tide/tide.go#L1253, I can see that this particular error is silenced intentionally. UX is a bit confusing here for someone who is not familiar with tide configurations.

**Comment by petr-muller** [comment]
We just discovered in https://github.com/openshift/jenkins-sync-plugin/pull/417 that this can actually block merges when this happens, which makes this worse than just UX problem. Tide gets stuck trying to merge the one PR that it cannot, and the other PRs eligible for merges wait.

**Comment by danilo-gemoli** [comment]
@petr-muller unfortunately it seems that Tide considers only a PR to be mergeable in general (that means: at least one merge method is allowed) to set a success status. That causes the PR to be processed over and over again, in an infinite loop. Even looking at the "jenkin rebase problem" it is not clear to me how that could block other PRs that are in the same pool. Can you give me a little bit more context to replicate the bug?
In any case GitHub provides a preview feature in order to determine if a PR is rebase-able or not, even without requesting a "real" merge; that could be useful to handle this situation better.

**Comment by petr-muller** [comment]
>  Can you give me a little bit more context to replicate the bug?

I saw Tide trying to merge one of the PRs that got into this state, and it apparently prevented Tide from getting to other eligible PRs (that did not have this conflict). I did not investigate it further, but when we closed the problematic PR, the other ones got merged immediately. So maybe the problematic was just the first in some list and Tide never got over it or something like that.

**Comment by danilo-gemoli** [comment]
I have replicated the issue locally and I agree with you on the analysis. Yesterday I opened a PR that should solve this problem and it has been merged, so let's monitor it to check if it will happen again.

**Comment by petr-muller** [comment]
Let's close the issue then. We can always reopen when someone brings the evidence that this was not fixed.

**Comment by JohnNiang** [comment]
I encountered this issue recently, please see logs in tide container:

```go
tide-5bc87f687-qfv9t {"component":"tide","controller":"sync","error":"failed to merge: merge strategy \"rebase\" is not supported","file":"k8s.io/test-infra/prow/tide/tide.go:1663","func":"k8s.io/test-infra/prow/tide.(*Controller).presubmitsByPull","level":"debug","msg":"Failed to get presubmits for PR, excluding from subpool","severity":"debug","time":"2022-04-14T11:50:13Z"}
```

And I found the possible related code below:

Please see 

https://github.com/kubernetes/test-infra/blob/0e1f55da5401d8ebd359fb8c5df3f7924e041f36/prow/tide/tide.go#L1096

https://github.com/kubernetes/test-infra/blob/e38ba360f2e51917cea9bc95ef54a7e7a8f026fe/prow/git/git.go#L377-L387
