### ISSUE TITLE
run_after_success presubmit jobs aren't working properly

### ISSUE THREAD

**Issue by luxas** [kubernetes/test-infra#4504]
See: http://prow.k8s.io/?job=pull-kubernetes-e2e-kubeadm-gce
Basically, less than 10% of the jobs even start.
@krzyzacy said that the GCE canary job that is also hooked up after the bazel presubmit suffers from the same bug(s).

Basically, if a presubmit is hooked up after an other, the "child" job should always be executed if `run_if_changed` passes. Right now those child jobs don't seem to be spawned correctly.

I'm not sure even where to start looking.
@krzyzacy @fejta @BenTheElder @pipejakob Any suggestions/pointers?

**Comment by krzyzacy** [comment]
cc @spxtr @kargakis

**Comment by kargakis** [comment]
[max_concurrency](https://github.com/kubernetes/test-infra/blob/917f59061fd5787db77f10cdfd2d6d71104273b1/prow/config.yaml#L140) is currently broken for kubernetes jobs and it seems that this job is using it. Someone with access to plank logs should be able to confirm it.

**Comment by pipejakob** [comment]
If the presubmit job is using Boskos, do we really need to set max_concurrency? Is this just a best practice for prow, or can we remove it since we shouldn't be hitting quota issues?

**Comment by krzyzacy** [comment]
@pipejakob we probably don't want 100 copy of the job running at the same time, which will drain the project pool. (It should not really happen, but just in case,  I would still keep some protection around.)

**Comment by kargakis** [comment]
I would suggest removing max_concurrency for now to allow the job to run. I can push forward wrapping up https://github.com/kubernetes/test-infra/pull/4468 and once it merges, we can re-enable the option? @krzyzacy sgty?

**Comment by krzyzacy** [comment]
@kargakis is it going to open the floodgate and trigger all those 100 pending instance at the same time?

**Comment by kargakis** [comment]
No, those prowjobs will stay pending forever because their MaxConcurrency is set and the in-memory pendingJobs cache in plank won't allow them to run. Even when you redeploy plank, this will not be a problem.

**Comment by luxas** [comment]
Interestingly enough, all batch jobs are passing: http://prow.k8s.io/?type=batch&job=pull-kubernetes-e2e-kubeadm-gce

@kargakis Yeah, I know `max_concurrency` isn't ready for the prime time. Please ping me when it is and we can make the job start reporting.

@krzyzacy Do you know if `run_if_changed` is respected for `run_after_success` jobs?

**Comment by BenTheElder** [comment]
Note that `max_concurrency` is hopefully generally fixed now. Thanks @kargakis!

**Comment by luxas** [comment]
The presubmit is still not running properly on normal PRs and `run_if_changed` is not respected.
@krzyzacy can you look into the `run_if_changed` thing?
@kargakis LMK if something needs to be done on my side to make `max_concurrency` work...

**Comment by kargakis** [comment]
> @krzyzacy can you look into the run_if_changed thing?

Can you open a PR and move the job as a top-level job in the config? run_if_changed and always_runs never worked for run_after_success jobs. cc: @krzyzacy

**Comment by luxas** [comment]
@kargakis can't do that, as out job actually depends on the bazel one.
cc @pipejakob 

Let's instead fix the issues with `run_after_success`

**Comment by krzyzacy** [comment]
I don't have bandwidth now -  can you send a PR? Or flip always_run for now?

**Comment by luxas** [comment]
`always_run` doesn't work either... :(
tbh, I don't understand exactly where the current issue is

**Comment by kargakis** [comment]
@luxas bad timing. plank:0.43 needs to run for one day before redeploying 0.44 that contains the max_concurrency fix. Not sure how are we going to deploy a possible fix for `run_after_success` jobs. Maybe fix it on a separate branch that doesn't contain the max_concurrency changes, and apply it also on top of the max_concurrency fix? cc: @spxtr

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/test-infra/pull/4586

**Comment by luxas** [comment]
Thanks @kargakis!

**Comment by luxas** [comment]
@kargakis @krzyzacy et al, can we reopen this to make the jobs respect `run_if_changed`?
