### ISSUE TITLE
Failing to find godep in 'ci-perf-tests-kubemark-100-benchmark' job

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/test-infra#5053]
The make target is continuously failing due to not finding 'godep' (ref: https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100-benchmark):

```
I1018 09:35:24.780] go get -u github.com/tools/godep
I1018 09:35:41.080] GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -a -o build/benchmark cmd/benchmark.go
I1018 09:35:41.081] Makefile:25: recipe for target 'benchmark' failed
W1018 09:35:41.089] /bin/sh: 1: godep: not found
```

while running the make target locally works for me. Note that we're using the 'execute' scenario for the job.

/cc @krzyzacy Could you PTAL or redirect as apt?

**Comment by krzyzacy** [comment]
hummmm seems we lost `godep` in the image? I'll add that back

**Comment by krzyzacy** [comment]
nope it's running `go get -u github.com/tools/godep` though

**Comment by BenTheElder** [comment]
should be fixed by #5056

**Comment by shyamjvs** [comment]
That was fast! Thanks @krzyzacy :)

**Comment by shyamjvs** [comment]
Seems like the issue still persists - https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100-benchmark

**Comment by krzyzacy** [comment]
@shyamjvs seems the go program crashed, can you give me more context?

**Comment by shyamjvs** [comment]
/assign

I'll take a look into it. It's some issue with the benchmark job configuration.
