### ISSUE TITLE
CI jenkins never uploads finished.json

### ISSUE THREAD

**Issue by fejta** [kubernetes/test-infra#777]
kubekins has a red notification box about some plugin errors:

```
conditional-buildstep v1.3.3 failed to load. Fix this plugin first.
conditional-buildstep v1.3.3
```

I suspect this means the conditional-buildstep is not running, which means we never upload finished.json

**Comment by ixdy** [comment]
I think this is fixed now - can we close?

**Comment by wojtek-t** [comment]
If this is the same as https://github.com/kubernetes/kubernetes/issues/34446 (what @ixdy suggested), then it's not fully fixed. We still not have logs from kubemark suites.

**Comment by fejta** [comment]
Most builds are now uploading so let's close out this one. Let's keep the kubernetes bug open and use it to deal with the kubemark logging. Sorry things are failing for you :(
